"""OOB ledger export: game state -> markdown attrition ledger.

The order-of-battle ledger (CLAUDE.md, Phase 1) tracks formations,
equipment, and attrition state by chapter. The campaign instrument
IS that ledger's data source: this module renders a run's end state
and day log into the ledger's format, so gamed campaigns and the
manuscript's continuity bookkeeping share one spine.

Usage: python -m wargame <scenario> --ledger out.md
"""


def _strength_bar(s):
    filled = round(s * 10)
    return "#" * filled + "." * (10 - filled)


def _unit_rows(force, status):
    rows = []
    for u in force:
        rows.append(
            f"| {u.name} | {u.kind} | {_strength_bar(u.strength)} "
            f"{u.strength:>4.0%} | {status} |"
        )
    return rows


def render(meta, params, axes, state, logs, days, camp=None):
    out = []
    out.append(f"# Campaign ledger: {meta.get('name', 'unnamed')}")
    out.append("")
    out.append(
        f"Seed {meta.get('seed', '?')}, {days} days, "
        f"deep_fraction={params.get('deep_fraction', 0.0)}, "
        f"deep_target={params.get('deep_target', 'echelon')}, "
        f"apportionment={params.get('apportionment_mode', 'direct')}, "
        f"red_amphib={params.get('red_amphib', 'threat')}. "
        "Generated by wargame vs. this scenario's committed state; "
        "regenerate, don't hand-edit."
    )
    out.append("")

    # Theater pools (v8-v11): forces that belong to no axis are still
    # the ledger's business — continuity bookkeeping must see them.
    if camp is not None:
        pools = [
            ("Corps reserve (undispatched)", camp.corps_reserve),
            ("Amphib package (staged)", camp.amphib_pool),
            ("Zealand garrison (kept)", camp.zealand_garrison),
        ]
        if any(units for _, units in pools):
            out.append("## Theater pools")
            out.append("")
            out.append("| Unit | Kind | Strength | Status |")
            out.append("|---|---|---|---|")
            for label, units in pools:
                out.extend(_unit_rows(units, label))
            out.append("")
        if getattr(camp, "zealand_lost", False):
            out.append("**ZEALAND LOST** — the landing succeeded.")
            out.append("")

    for name, ax in axes.items():
        st = state[name]
        status = "FALLEN" if st.fallen else "holding"
        out.append(
            f"## Axis: {name} — FEBA {st.feba_km:.0f}/{st.length_km:.0f} km [{status}]"
        )
        out.append("")
        for side in ("blue", "red"):
            f = ax[side]
            out.append(f"### {side.upper()} (CV {f.cv:.1f} in line)")
            out.append("")
            out.append("| Unit | Kind | Strength | Status |")
            out.append("|---|---|---|---|")
            out.extend(_unit_rows(f.units, "line"))
            out.extend(_unit_rows(f.withheld, "withheld reserve"))
            out.extend(_unit_rows(f.staging, "staging"))
            out.extend(_unit_rows(f.reserve, "not yet arrived"))
            out.append("")

    out.append("## Day log (theater)")
    out.append("")
    out.append(
        "| Day | Axis | FEBA | Ratio | Blue loss | Red fill | Deep | Zeal-c | Flags |"
    )
    out.append("|---|---|---|---|---|---|---|---|---|")
    for e in logs:
        flags = "".join(
            [
                "C" if e.ca else "",
                "S" if e.standing else "",
                "P" if e.pause else "",
                "N" if e.air_naval else "",
                f" +{e.arrivals}re" if e.arrivals else "",
                f" +{e.blue_arrivals}bl" if e.blue_arrivals else "",
            ]
        )
        out.append(
            f"| {e.day} | {e.axis} | {e.feba_km:.0f} | {e.ratio} "
            f"| {e.blue_loss_frac:.1%} | {e.rfill:.0%} "
            f"| {e.deep_frac:.2f} | {e.zeal_c:.2f} | {flags} |"
        )
    out.append("")
    return "\n".join(out)
